apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: newsgradient-bih-parser
spec:
  schedule: "0,30 * * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 2
  jobTemplate:
    spec:
      backoffLimit: 1
      template:
        spec:
          containers:
          - name: newsgradient-bih-parser
            image: newsgradient-bosna-parser
            env:
            - name: DJANGO_SETTINGS_MODULE
              value: newsgradient.settings
            envFrom:
              - secretRef:
                  name: newsgradient-api-credentials
            resources:
              requests:
                memory: 400Mi
                cpu: 100m
              limits:
                memory: 400Mi
                cpu: 100m
          restartPolicy: Never
