apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: newsgradient
resources:
  - api/deployment.yaml
  - api/service.yaml
  - api/ingress.yaml
  - api/pvc.yaml
  - api/refresh_articles.yaml
  - api/fetch_tweets.yaml
  - api/send_newsletter.yaml
  - pwa/deployment.yaml
  - pwa/service.yaml
  - pwa/ingress.yaml
  - parser/cronjob.yaml
images:
  - name: newsgradient-api
    newName: rg.fr-par.scw.cloud/djnd/newsgradient-api
    newTag: 'b9ad4f44acd7a3559c02d2063d2b5ba941a071b9'
  - name: newsgradient-pwa
    newName: rg.fr-par.scw.cloud/djnd/newsgradient-pwa
    newTag: 'b9ad4f44acd7a3559c02d2063d2b5ba941a071b9'
  - name: newsgradient-bosna-parser
    newName: rg.fr-par.scw.cloud/djnd/newsgradient-bosna-parser
    newTag: 'b9ad4f44acd7a3559c02d2063d2b5ba941a071b9'
