apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: newsgradient
resources:
  - api/deployment.yaml
  - api/service.yaml
  - api/ingress.yaml
  - api/pvc.yaml
  - api/refresh_articles.yaml
  - pwa/deployment.yaml
  - pwa/service.yaml
  - pwa/ingress.yaml
images:
  - name: newsgradient-api
    newName: rg.fr-par.scw.cloud/djnd/newsgradient-api
    newTag: 'd02948b59c89defe2601c46a9683ef962841b4b0'
  - name: newsgradient-pwa
    newName: rg.fr-par.scw.cloud/djnd/newsgradient-pwa
    newTag: 'd02948b59c89defe2601c46a9683ef962841b4b0'
