apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: newsgradient
resources:
  - api/deployment.yaml
  - api/service.yaml
  - api/ingress.yaml
  - api/pvc.yaml
  - api/refresh_articles.yaml
  - pwa/deployment.yaml
  - pwa/service.yaml
  - pwa/ingress.yaml
images:
  - name: newsgradient-api
    newName: rg.fr-par.scw.cloud/djnd/newsgradient-api
    newTag: 'a92f94071637b85b764ae9170f11a4852aae65ea'
  - name: newsgradient-pwa
    newName: rg.fr-par.scw.cloud/djnd/newsgradient-pwa
    newTag: 'a92f94071637b85b764ae9170f11a4852aae65ea'
