apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: newsgradient
resources:
  - api/deployment.yaml
  - api/service.yaml
  - api/ingress.yaml
  - api/pvc.yaml
  - api/refresh_articles.yaml
  - api/fetch_tweets.yaml
  - pwa/deployment.yaml
  - pwa/service.yaml
  - pwa/ingress.yaml
images:
  - name: newsgradient-api
    newName: rg.fr-par.scw.cloud/djnd/newsgradient-api
    newTag: '948f05fcd872a68c7ef1e93dde879f4f0e3c0f7e'
  - name: newsgradient-pwa
    newName: rg.fr-par.scw.cloud/djnd/newsgradient-pwa
    newTag: '948f05fcd872a68c7ef1e93dde879f4f0e3c0f7e'
