apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: newsgradient
resources:
  - api/deployment.yaml
  - api/service.yaml
  - api/ingress.yaml
  - api/pvc.yaml
  - api/refresh_articles.yaml
  - api/fetch_tweets.yaml
  - api/send_newsletter.yaml
  - pwa/deployment.yaml
  - pwa/service.yaml
  - pwa/ingress.yaml
images:
  - name: newsgradient-api
    newName: rg.fr-par.scw.cloud/djnd/newsgradient-api
    newTag: 'b64e2fb431092164a19db1cc9a9f897165496a3e'
  - name: newsgradient-pwa
    newName: rg.fr-par.scw.cloud/djnd/newsgradient-pwa
    newTag: 'b64e2fb431092164a19db1cc9a9f897165496a3e'
