# Generated by Django 3.2.4 on 2022-08-31 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Name')),
                ('link', models.URLField(blank=True, null=True, verbose_name="Media's link")),
                ('fb_link', models.URLField(blank=True, null=True, verbose_name='Facebook link')),
                ('tw_link', models.URLField(blank=True, null=True, verbose_name='Twitter link')),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('actor_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='analize.actor')),
            ],
            bases=('analize.actor',),
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('actor_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='analize.actor')),
            ],
            bases=('analize.actor',),
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='Title')),
                ('content', models.TextField(verbose_name='Content')),
                ('link', models.URLField(blank=True, null=True, verbose_name='News link')),
                ('html', models.TextField(verbose_name='Content')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Published at')),
                ('parsed_at', models.DateTimeField(blank=True, null=True, verbose_name='Parsed at')),
                ('last_parsed_at', models.DateTimeField(blank=True, null=True, verbose_name='Last parsed at')),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analize.media', verbose_name='Media')),
                ('members', models.ManyToManyField(related_name='news', to='analize.Member', verbose_name='Members')),
                ('parties', models.ManyToManyField(related_name='news', to='analize.Party', verbose_name='Parties')),
            ],
        ),
    ]
