# Generated by Django 3.2.4 on 2022-09-01 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analize', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='location',
            field=models.CharField(choices=[('KS', 'Kanton Sarajevo'), ('RS', 'Republika Srpska'), ('US', 'Unsko-Sanski kanton'), ('HN', 'Hercegovačko-neretvanski kanton'), ('TK', 'Tuzlanski kanton'), ('ZD', 'Zeničko-dobojski kanton'), ('BD', 'Brčko distrikt')], default='KS', max_length=2, verbose_name="Media's location"),
        ),
    ]
