# Generated by Django 3.2.4 on 2022-09-01 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analize', '0002_media_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='members',
        ),
        migrations.RemoveField(
            model_name='news',
            name='parties',
        ),
        migrations.AddField(
            model_name='actor',
            name='parser_names',
            field=models.TextField(default=1, verbose_name='Parser names divided with |'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='news',
            name='html',
            field=models.TextField(verbose_name='Html content'),
        ),
        migrations.CreateModel(
            name='PartyNewsMention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(blank=True, null=True, verbose_name='Score')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partynews_through', to='analize.news', verbose_name='News')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parties_through', to='analize.party', verbose_name='Party')),
            ],
        ),
        migrations.CreateModel(
            name='MembersNewsMention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(blank=True, null=True, verbose_name='Score')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members_through', to='analize.member', verbose_name='Member')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membernews_through', to='analize.news', verbose_name='News')),
            ],
        ),
    ]
