# Generated by Django 3.2.4 on 2022-09-01 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analize', '0003_auto_20220901_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='members',
            field=models.ManyToManyField(related_name='news', through='analize.MembersNewsMention', to='analize.Member', verbose_name='Members'),
        ),
        migrations.AddField(
            model_name='news',
            name='parties',
            field=models.ManyToManyField(related_name='news', through='analize.PartyNewsMention', to='analize.Party', verbose_name='Parties'),
        ),
    ]
