# Generated by Django 3.2.4 on 2022-09-20 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analize', '0005_alter_news_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='in_party',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='members', to='analize.party', verbose_name='Party'),
        ),
        migrations.AlterField(
            model_name='news',
            name='media',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news', to='analize.media', verbose_name='Media'),
        ),
    ]
