# Generated by Django 3.2.4 on 2023-10-02 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analize', '0007_alter_actor_parser_names'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartyMediaScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Score')),
                ('neutral_score', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Neutral score')),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partymediascore', to='analize.media', verbose_name='Media')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partymediascore', to='analize.party', verbose_name='Party')),
            ],
        ),
    ]
