# Generated by Django 3.0.6 on 2021-07-28 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_auto_20200715_1231'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('twitter_id', models.TextField(unique=True)),
                ('timestamp', models.DateTimeField(null=True)),
                ('text', models.TextField()),
                ('retweet', models.BooleanField(default=False)),
                ('retweet_timestamp', models.DateTimeField(null=True)),
                ('retweet_id', models.TextField(null=True)),
                ('retweet_quote', models.BooleanField(default=False)),
                ('retweet_quote_url', models.URLField(null=True)),
                ('quote', models.BooleanField(default=False)),
                ('quote_url', models.URLField(null=True)),
                ('favorite_count', models.IntegerField(null=True)),
                ('retweet_count', models.IntegerField(null=True)),
                ('user_handle', models.TextField()),
            ],
        ),
    ]
