# Generated by Django 3.0.6 on 2021-07-28 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_tweet'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='news.Article'),
        ),
    ]
