# Generated by Django 3.2.4 on 2021-09-03 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_tweet_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='article',
            name='uri',
            field=models.TextField(max_length=25, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='event',
            name='uri',
            field=models.TextField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='medium',
            name='slant',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Left'), (2, 'Neutral'), (3, 'Right')], null=True),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tweets', to='news.article'),
        ),
    ]
