# Generated by Django 3.2.4 on 2021-09-06 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_auto_20210906_0744'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='sentiment',
        ),
        migrations.RemoveField(
            model_name='event',
            name='summary',
        ),
        migrations.RemoveField(
            model_name='event',
            name='wgt',
        ),
    ]
