# Generated by Django 3.0.6 on 2021-10-05 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0011_auto_20210906_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='images',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('sent', models.BooleanField(default=False)),
                ('events', models.ManyToManyField(blank=True, help_text='Events to include in the newsletter', to='news.Event')),
            ],
        ),
    ]
