# Generated by Django 3.2.4 on 2023-10-04 09:30

from django.db import migrations

def copy_analize_data(apps, schema_editor):
    AnalizeParty = apps.get_model("analize", "Party")
    NewsParty = apps.get_model("news", "Party")

    parties = AnalizeParty.objects.all()
    for party in parties:
        NewsParty(
            name=party.name,
            parser_names=party.parser_names
        ).save()

class Migration(migrations.Migration):

    dependencies = [
        ('news', '0014_auto_20231004_0930'),
    ]

    operations = [
        migrations.RunPython(copy_analize_data),
    ]
