# Generated by Django 3.2.4 on 2023-10-04 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0015_auto_20231004_0930'),
    ]

    operations = [
        migrations.AddField(
            model_name='medium',
            name='location',
            field=models.CharField(choices=[('KS', 'Kanton Sarajevo'), ('RS', 'Republika Srpska'), ('US', 'Unsko-Sanski kanton'), ('HN', 'Hercegovačko-neretvanski kanton'), ('TK', 'Tuzlanski kanton'), ('ZD', 'Zeničko-dobojski kanton'), ('BD', 'Brčko distrikt')], default='KS', max_length=2, verbose_name="Media's location"),
        ),
    ]
