# Generated by Django 3.2.4 on 2023-10-04 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0016_medium_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medium',
            name='location',
            field=models.CharField(choices=[('FBIH', 'FBIH'), ('HBŽ', 'HBŽ'), ('SŽ', 'SŽ'), ('ŽZH', 'ŽZH'), ('ZDŽ', 'ZDŽ'), ('USŽ', 'USŽ'), ('HNŽ', 'HNŽ'), ('ŽSB', 'ŽSB'), ('BPŽ', 'BPŽ'), ('TŽ', 'TŽ'), ('RS', 'RS'), ('Brčko', 'Brčko')], default='FBIH', max_length=5, verbose_name="Media's location"),
        ),
    ]
