from analize.models import Media, Party

from django.core.management.base import BaseCommand

mediums = [
    'aljazeera',
    'aloonline',
    'atvbl',
    'banjeluka',
    'bhindex',
    'bhrt',
    'biscani',
    'bljesak',
    'blportal',
    'bosnainfo',
    'buka',
    'cazin',
    'depo',
    'dnevnik',
    'face',
    'faktor',
    'federalna',
    'fokus',
    'glassrpske',
    'haber',
    'hayat',
    'hercegovinainfo',
    'jabuka',
    'klix',
    'logicno',
    'mojabanjaluka',
    'n1info',
    'nap',
    'nezavisne',
    'oslobodjenje',
    'poskok',
    'pressmediabih',
    'radiosarajevo',
    'raport',
    'rediokameleon',
    'rtrs',
    'rtvbn',
    'saff',
    'slobodnabosna',
    'source',
    'srpskainfo',
    'stav',
    'tacno',
    'tip',
    'tuzlanski',
    'vecernji',
    'vijesti',
    'zenit',
    'zurnal',
]

parties = [
    'Narod i pravda',
    'NiP',
    'Socijaldemokratska partija Bosne i Hercegovine',
    'SDP BiH',
    'Stranka demokratske akcije',
    'SDA',
    'Pokret demokratske akcije BiH',
    'PDA BiH',
    'PDA',
    'Partija demokratskog progresa',
    'PDP',
    'Ujedinjena Srpska',
    'Narodni Evropski Savez Bosne i Hercegovine',
    'NES BiH',
    'NES',
    'Hrvatska stranka prava dr. Ante Starčević Bosne i Hercegovine',
    'HSP dr. Ante Starčević BiH',
    'Narodni demokratski pokret',
    'NDP',
    'Građanski savez',
    'GS',
    'Srpska demokratska stranka',
    'SDS',
    'Socijalistička partija Republike Srpske',
    'SP RS',
    'SPRS',
    'Nezavisni blok',
    'NB',
    'Savez za bolju budućnoost',
    'SBB',
    'Hrvatska demokratska zajednica Bosne i Hercegovine',
    'HDZ BiH',
    'Hrvatska demokratska zajednica 1990',
    'HDZ 1990',
    'Savez Nezavisnih socijaldemokrata',
    'SNSD',
    'Demokratska fronta',
    'DF',
    'Naša stranka',
    'NS',
    'Laburistička stranka',
    'Demokratski narodni savez',
    'DNS',
]
class Command(BaseCommand):
    help = 'Setup data'
    def handle(self, *args, **options):
        for media in mediums:
            Media(name=media).save()

        for party in parties:
            Party(name=party).save()

