apiVersion: apps/v1
kind: Deployment
metadata:
  name: newsgradient-api-deployment
  labels:
    app: newsgradient-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: newsgradient-api
  template:
    metadata:
      labels:
        app: newsgradient-api
    spec:
      initContainers:
        - name: collectstatic
          image: newsgradient-api
          command:
            - python
            - manage.py
            - collectstatic
            - --no-input
          env:
            - name: DJANGO_SETTINGS_MODULE
              value: newsgradient.settings
          envFrom:
            - secretRef:
                name: newsgradient-api-credentials
          resources:
            requests:
              memory: 400Mi
              cpu: 100m
            limits:
              memory: 400Mi
              cpu: 100m
        - name: migrate
          image: newsgradient-api
          command:
            - python
            - manage.py
            - migrate
          env:
            - name: DJANGO_SETTINGS_MODULE
              value: newsgradient.settings
          envFrom:
            - secretRef:
                name: newsgradient-api-credentials
          resources:
            requests:
              memory: 400Mi
              cpu: 100m
            limits:
              memory: 400Mi
              cpu: 100m
      containers:
        - name: newsgradient-api
          image: newsgradient-api
          command:
            - gunicorn
            - newsgradient.wsgi:application
            - -b
            - 0.0.0.0:8000
            - --log-level
            - DEBUG
          ports:
            - containerPort: 8000
          envFrom:
              - secretRef:
                  name: newsgradient-api-credentials
          env:
            - name: DJANGO_SETTINGS_MODULE
              value: newsgradient.settings
          resources:
            requests:
              memory: 400Mi
              cpu: 100m
            limits:
              memory: 400Mi
              cpu: 100m
