apiVersion: batch/v1
kind: Job
metadata:
  name: newsgradient-export-bosnian-news
spec:
  template:
    spec:
      containers:
        - name: newsgradient-fetch-tweets
          image: newsgradient-api
          env:
            - name: DJANGO_SETTINGS_MODULE
              value: newsgradient.settings
          envFrom:
            - secretRef:
                name: newsgradient-api-credentials
        command:
          - python
          - manage.py
          - export_news
      restartPolicy: Never
  backoffLimit: 1
