apiVersion: batch/v1
kind: Job
metadata:
  name: newsgradient-export-bosnian-news
spec:
  template:
    spec:
      containers:
        - name: newsgradient-export-bosnian-news
          image: newsgradient-api
          env:
            - name: DJANGO_SETTINGS_MODULE
              value: newsgradient.settings
          envFrom:
            - secretRef:
                name: newsgradient-api-credentials
          command:
            - python
            - manage.py
            - export_news
          resources:
            requests:
              memory: 500Mi
              cpu: 200m
            limits:
              memory: 500Mi
              cpu: 200m
      restartPolicy: Never
  backoffLimit: 1
