apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: newsgradient-fetch-tweets
spec:
  schedule: "5 * * * *" # every hour
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: newsgradient-fetch-tweets
            image: newsgradient-api
            env:
              - name: DJANGO_SETTINGS_MODULE
                value: newsgradient.settings
            envFrom:
              - secretRef:
                  name: newsgradient-api-credentials
            command:
              - python
              - manage.py
              - fetch_tweets
            resources:
              requests:
                memory: 500Mi
                cpu: 200m
              limits:
                memory: 500Mi
                cpu: 200m
          restartPolicy: OnFailure
