apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: newsgradient-refresh-articles
spec:
  schedule: "0 5,7,12,14,16,18 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: newsgradient-refresh-articles
            image: newsgradient-api
            env:
              - name: DJANGO_SETTINGS_MODULE
                value: newsgradient.settings
            envFrom:
              - secretRef:
                  name: newsgradient-api-credentials
            command:
              - python
              - manage.py
              - fetch_new_articles
            resources:
              requests:
                memory: 500Mi
                cpu: 200m
              limits:
                memory: 500Mi
                cpu: 200m
          restartPolicy: OnFailure
